### ISSUE TITLE
Проверка дз

### ISSUE THREAD

**Issue by Rainbowdm** [AnnaPozina/Lesson5#1]
https://github.com/AnnaPozina/Lesson5/blob/dde3ff54671ebd8106dd0769b8091f679f68a04f/src/test/java/registration/contactUs.java#L59

Не увидел здесь проверку конкретного сообщения
Посмотри что делает метод  isDisplayed()

Добавь проверку на текст, у меня указан текст который должен получиться и сравнить с тем который вытянешь из страницы

**Comment by AnnaPozina** [comment]
написала проверку

**Comment by Rainbowdm** [comment]
отлично
